### ISSUE TITLE
I think there are errors in drawing sign-restricted IRFs when the number of exogenous variables is more than two.

### ISSUE THREAD

**Issue by SangJL** [naffe15/BVAR_#9] opened 2021-12-10 05:53 UTC
When bvar_.m gets the IRF with sign restrictions, it uses the following codes(line number 900):

    % with sign restrictions
    if signs_irf == 1        
        [irsign,Omega]         = iresponse_sign(Phi,Sigma,hor,signs);
        irsign_draws(:,:,:,d)  = irsign;
        Omega_draws(:,:,d)     = Omega;
    end

But, since Phi includes not only values for endogenous variables but also values for exogenous variables, iresponse_sign function returns wrong IRF when the number of exogenous variables is more than two.

I believe the following codes will work:

        [irsign,Omega]         = iresponse_sign(Phi(1:(size(Phi,1)-nexogenous),:),Sigma,hor,signs);

**Comment by SangJL** [comment] 2021-12-13 09:06
Hello,

If I changed codes in exmple_6_VARX.m to include two exogenous variables and to use sign restrictions as following, current bar_.m doesn't work well in producing IRFs

% exogenous variable
z = demean(100*diff(log ([cpi_us str_us] )));
% include one lag for the exogenous variable
options.controls = lagX(z,[0:1]);
options.signs{1}    = 'y(4,1:3,4)>0';
options.signs{2}    = 'y(2,1:3,4)<0';

% estimate the VARX
bvar1       = bvar_(y,lags,options); 

indx_sho              = 4; 
indx_var              = [1, 2, 3, 4];
irfs_to_plot           = bvar1.irsign_draws(:,:,indx_sho,:);
%%%%

But I found that bar_.m works well  with my suggestions.

**Comment by naffe15** [comment] 2021-12-13 17:47
Hi, 
thanks for the follow up. now I understand where the problem is. the functions calculating the IRFs were computing the wrong number of lags when more than one exogenous variable is used. This problem is fixed now. thanks for spotting this. 
f.

**Comment by SangJL** [comment] 2021-12-14 02:11
My pleasure!

**Comment by SangJL** [comment] 2021-12-14 04:56
Could I ask one more improvement?

Even though I set "options.K = 1000;", I may not get 1,000 draws because d =0 in "iresponse_sign.m" for cases. In my experiments, I can see the warning,"I could not find a rotation satisfying the restrictions.", for about 5~10% draws out of total designated draws(options.K). So, could you improve your "bvar_.m" to ensure that I can get initially-designed number of draws(options.K).

**Comment by naffe15** [comment] 2021-12-14 08:50
I will look into it. 
f.

**Comment by SangJL** [comment] 2021-12-14 09:09
Appreciated!

**Closed** 2023-06-22 14:28 UTC
